apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
spec:
  restartPolicy: Never
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: busybox-pod
      image: busybox
      command:
        - /bin/sh
        - '-c'
        - while true; do sleep 3600; done
      volumeMounts:
        - name: shared-data
          mountPath: /tmp/data
    - name: nginx-pod
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /data